allowBuilds:
    "@parcel/watcher": true
    esbuild: true
    sharp: true
catalog:
    vite: npm:@voidzero-dev/vite-plus-core@0.2.4
    vite-plus: 0.2.4
minimumReleaseAgeExclude:
    - "@origami-systems/*"
    - "@astrojs/check@0.9.10"
    - "@astrojs/mdx@7.0.4"
    - astro@7.1.4
    - "@astrojs/compiler-binding-darwin-arm64@0.4.0"
    - "@astrojs/compiler-binding-darwin-x64@0.4.0"
    - "@astrojs/compiler-binding-linux-arm64-gnu@0.4.0"
    - "@astrojs/compiler-binding-linux-arm64-musl@0.4.0"
    - "@astrojs/compiler-binding-linux-x64-gnu@0.4.0"
    - "@astrojs/compiler-binding-linux-x64-musl@0.4.0"
    - "@astrojs/compiler-binding-wasm32-wasi@0.4.0"
    - "@astrojs/compiler-binding-win32-arm64-msvc@0.4.0"
    - "@astrojs/compiler-binding-win32-x64-msvc@0.4.0"
    - "@astrojs/compiler-binding@0.4.0"
    - "@astrojs/compiler-rs@0.4.0"
overrides:
    vite: "catalog:"
peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: "*"
