allowBuilds:
    "@parcel/watcher": true
    esbuild: true
    sharp: true
catalog:
    vite: npm:@voidzero-dev/vite-plus-core@0.2.4
    vite-plus: 0.2.4
minimumReleaseAgeExclude:
    - "@origami-systems/*"
    - "@astrojs/check@0.9.10"
    - "@astrojs/mdx@7.0.4"
    - astro@7.1.4
overrides:
    vite: "catalog:"
peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: "*"
